# Python project, check against all supported things.
language: python

matrix:
  include:
    - os: linux
      python: 2.7
      dist: xenial
      sudo: required
    - os: linux
      python: 3.4
      dist: xenial
      sudo: required
    - os: linux
      python: 3.5
      dist: xenial
      sudo: required
    - os: linux
      python: 3.6
      dist: xenial
      sudo: required
    - os: linux
      python: 3.7
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode11
      language: shell
      before_install:
      - brew update -q
      - brew outdated python || brew upgrade python

# disable submodules from git
git:
  submodules: false
# commands to install dependencies
install:
  - 'if [ -x "$(command -v apt-get)" ]; then sudo apt-get install scons chrpath; fi'
  - "pip install -r requirements-devel.txt"
  - "pip install ."
# commands to run tests
script:
  - env | sort
  - ./tests/run-tests --no-other-python --skip-reflection-test --skip-all-cpython-tests
  - 'if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then ./bin/check-nuitka-with-restlint; fi'
  - ./bin/check-nuitka-with-pylint --not-installed-is-no-error
